#!/bin/bash

count=100
if [ $# -eq 1 ]; then
  count=$1
fi

for i in $(seq 1 $count); do
  tput setaf $(($RANDOM % 7 + 1))
  for j in {1..3}; do
    case $j in
      1) echo ' /\_/\ ';;
      2) echo '( o.o )';;
      3) echo ' > ^ < ';;
    esac
    sleep 0.1
  done
  tput sgr0
done